---
- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-monitor-armada-app-upload-git-mirror

- job:
    name: stx-monitor-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/monitor-armada-app to
      github.com/starlingx/monitor-armada-app
    vars:
      git_mirror_repository: starlingx/monitor-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-monitor-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-monitor-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - e+Q2Y9KQdeT/52CeNFlYANqAwwnIRd+VMnjAsqkNqMYYX4sZUk6mYOvN3vlmY+gg9GtiC
          Ox+pf58jH14MHwyibqosJmbonjKr3MOKNEQ+mZNWQF0Bkq/HinTgBsCZk+ZJ1IVcxbinf
          ab8lWx2MI9YoDA5D+rRFrmgoI1yBhjFnEmmm7IjlOGN7w5iPjFMeWSoXSM+3p90J+3W1o
          FE0z4IJQr4qLK+nU60zVHpqjTfBoO+4MqKIS0IsSYFepckCDI3KxF6Xi4CigUcF9gy6BZ
          7KGEQRvhXYsT/8QbIIlBa8TMki80du738H764PlKkcEDHW+dReGUQaX8DETtbmUBh90pe
          qmtjjdDVLigZ8STpL78Ga36UXDpLH5ZSnFhM+9basrCExoHDXvkkY+HtATC5WpvtOGeAk
          475nl1P/Id4TjriXJYQs/+9J3YTJvXGqWhZLSbt2N4/xeqSFaSi6A3vhSOgz7wI+OF5Gj
          4lzdBdpxHZ2LUUbT9R+Blh8R9qdabtZeXoYFxEQwowZHOqiDa0PZE9bz83k5547/S69tc
          SeTRuXY5wDKQqeIm2J8HJaZqlY4tP7cZi7lAKPoft8Id3uEC+WOReorwaeeaTJ1/1LPtW
          ZnDAAFFE7iI+HpbSjP1K5ivEqqNGSiDicZ0/8Am4fRupfW833qgi/WeOiXiwqw=
        - NsCx8qBxKEseA+nPpt0WoxDOGFAysJvQRkdVB0fxPoc/AElwdMJ09qmdGoOyI1nN7HSgN
          A8/qDGYZexY9F1L46+SLeTHGFGnoiZur30kybmGFOVKSuT0XzeSJioMwOwxTd4Ov1DhFg
          RdV4+EMrVPMB1qxJY740yKh8zsOiFa1r+JBCbEu/T63tC/kEqiPxQxj3U4+Q8cXOaU2zb
          3UAM4N+VoZsYkEA/xLCP+va/jLNVgiJFB4I0zKEfmoA/T2n+EAByn3wnKtTAweVwDoCTs
          5743eM6z2w2tOU04qd4hnRL5E0SQ9MkeEiE2pEVwZXFDXPQciaJa0adQSR0jZcYoBwS8A
          v7sHFv3C5u+JFtQRByZAE7VvT8HdKn4EGWSmGhRchFBI+W+sP/JTPphcmxSCMZgBh7kev
          qgxN4YVoklooW59Oc9hG+rTEhudwqAkrJbyokULl707pE7jwzKrdK4PBWgpYw/trHDuZv
          rZRNVO5XGPAo2cyAP30XHT8Hr6lO7A37ofSLM1eIGfx37tPCqPEx01oJ/xJmC+Aq55fWM
          DEXzOFFzYqr0FSEwdZ0J5JrO3gQ6sGF/as+EauqD0QSBzmiBGHOLrRxV2UcR3kY7BcS3h
          mJd2bBHEHC92909PpCHhSrl7A0cW08jhFZncL2Z+nxC5q9tAfsNYJffSeLVhAA=
        - MW4ifVIo5pmVZPwBKpHKLGcoTFQEvfGjs4yEM+Losx5f8ZLYu/zIUVF1sYzfWyzCf8yj6
          /7oD1GuwXNwCtZ4l3PspxmXzf5C6IydWIfc5Y7kO7bWjAP09xy9ISjZTBYP6aimDgu7rj
          zjlXJ8NpkDxUYBQCDTVIYUHZLUrdfbqdzDekVgonZ/7e1oB9IFSAkQqyKs4dG9T6q11hQ
          ZvvPFT4s7tnnmn6jOxxIie5EDNhHslw4zQmwVo7Sjv7ZmHyVQvehn/AGwcjhe2kDF62qu
          5pb0oxhsU5dN5ngXdhTql/+m5GuTBPkJHit0oKO38V9b0ejHIVmM1lbSyIWRX7IlTfHjT
          mWtruCpXmIrNLk/XuerPbs1ldmgwQ4Wl1XnUrvE9QXCyu+YDm0KT1oATNbfpTtTHFPKIe
          oaBXfYKIbVah98Bj1Hg6u0BpW+w3t8JABxxW8JzT1b7dIr7absHFS3CiDDWUSuBU5OMhP
          cKq3xaIb4RuL5PZ5StgKUTDcA8W+HOnZ+HaoTj0gBjHufO9CZJ6ZR5N8iaRWkonyI3/Xw
          ilAEweNWm/kYUoDhB9IMSzxhHUfDsj4jthD2Dj5SRlagi/FDLlyWlP3LO8TTsu+nab+9z
          geyj4AJ2+yx6w3aH6fNQhpnUGq7NekE9y4V31IpbzrdEHEjFBUsFmSTBzy8LVo=
        - KPqr9EotX4LRqPTUwd+MYe2+F9tSecFtgQrLQ/vOh1qdDPBVxAxu9efcXvf3KOWKLba7s
          bngsFS7F6CZA/gKw9F62E1EvtgI6VW8Wx9hJjQTI8CHxfLQYovn0SVWhTzc0oAq18BAmG
          WwRsrbbsWYtCZAsFZpgdw85KzWXx0CTkkgfeoUExeDGE9zhERDqgri5yF/XzafchkDp6b
          P7MHGGE4LaBKTwR2gX1IC7pwyyafTeOW7XvAmRapyzKOW0A432tX4xwhH2bv/+Ira8MtM
          ORHEEnhw7xMKG5EVsmkC88YtFkW7g/epgxydrRqw1T9YKKFej6W4YKMv3mz1UepK+PZPF
          vWVHFL5w1ne/mcLQ1/LF8xozINo8/oil8H/Y++IIAkKl6Ob8neki6FbQ74eOXPntdkCy1
          MapA3nG6UZ9GgSitK58WbcnXJ19s5Hx117tACafKvHkIeAugZ1RYoYYSO3t+VAZFzBPGI
          GUkx1U/I0ZdA+b95uYYcpkYdp9UaT7a3iOqbw0iNFCPLfIWwjBpgBB5AlMTTiB3veNulv
          UVAcGNNCCrixs52tql5MmGxehV7WaAiRdokVA+WiXFnNBUbdWOrRj4yyHzzdM5pjH6ITO
          5m11kqV3/YdMmlxenmXvKxpHcpsjGS3A+levM1CurIykTcoD6QPCJBl1PWuHng=
        - D/xilUZoowTBLYSiBTcX1Eg/8oDlQbyjCHy042zWp1IZyhY5LNg89+BVJFB1McznIM/nk
          aaqhBbZ110/o6BbmQSMoOjx/1eu2wN1g20sIvjIi+ydsnVL+LdSlnFMXf3tnv0uV6Lc8u
          Cw4wz0ccCKyZ9fJaDh/ednq8s4b6DupCQO52TgmjYSQRRvG+p/xEYbiqLBqSk9gPJ665Q
          cx2cmjUi4fSUeYu3ZXCsI0pOnqGLHpcLLBuwLMiwcNwqR6HVwuAVMCKTCyMGrS5pViwFL
          l5YfgZOZhSIAQSrDFITXnT/YCn/POUk97owau6g2bINOdgBaVBDXw0gCm7jL+QJy9dXR+
          pVsaDJi2Jefhbg8QxvXrZPSzOO1HxGuSLYVsGXFJXGuBO4YWrIMNrdHR0Wd1Xie5T7Xlf
          KErmfolrO9YY69BWE4r7Zrs8at8m8tRb9kvQF6M5StGq4JI7Sg1G15BSRlI13e41MSzBC
          WnWdvZ6ZOUr0nAbidh5nUKqrbcQWfchEged37DXNmnDgPMQ3+ombulS3caYKOefsVkaFS
          rUvKrh7TmD1l9vHbN/CJspU3iNXzhk+MZRFQS5A85htgq5THyITEBCJqaKkhKCwweZgxy
          Xvqv7rsnx/HtqulFH7Ja1J3pF2dwzmryigqkKqICg6pKprHTExdJK21dVUQi0Q=
        - TCdwMFVeRef3sokOLVU2/+JDl/ojOg5rv6dKnnio1WYn8dMYxWMpQJ2CTPzImrXEDhVlg
          JKkDxFZfza0bF3ZnsoFWZ+t3GYILeRVsqaoMKmtYrCwhdG+ZOTtcKiusGdPIpi0lCBpAd
          ZwFgvTE46auaXN9VwXanSKAT/UhjEUMmhd5aVMVnJ2qY5C5BlQB+roeermNbEWybIj5Yy
          ax+B3/kCht6qztKWbiP0W8CsZfg1c81ktSqP3sTZrJkkpmg/XUsrlyngfIiKIswuPwA+M
          LNdD9HQbHV3lQ6VzxJQWQClfEGsZcXxweE+qkpco8amIi3UmEcxEfBz9TqGexqWgvL7KW
          qWWLKWkXxlPvd9sRgWt2edaHZBEKUFt6OyDxFJ2t1rNeQxzH0btKu1IN+HuetcWZ51RW5
          E6YkM51EohuTBtjFYjInivt0ADkjDqvW99Kj/54w4cU6rR6VVud1GwrmXdN0/EiypRzPw
          y9fhbavy4Ljl8YYO9ijJBG+G6tt3J3r0jucxIxd0ulRMuJtoxI294PVi571a7JwlJMk6w
          JWk0+zwTpOOGh8Ih9EvM96fM4ss29royfdplAL+JEkgGJVd6Kog2GwGHD80mx8g9Ha/xr
          5c7wpVTEnSTwtIKULkvAaEluTJgEb7slqZryeDXF+zuc825Ibxipg2CM5GdfRk=
        - kU454QAroJn5ri3MTRa0CYzCMg2ZoLCsdyMuu5176/6ORIRqd/fHqz+P5hGbEW7Sm0B9N
          EJj9tsIO+9Fie78k7D+I7t6P+9ExeyUTqPp/X2Dxzday/MxUzY/v7XTYcEFmNtswWAg3/
          UxcCKUE5fGZI7lic4Zf49bx783WaZ/+MkTSAMN8zf+IlYojhfy/XqC+Qvv0iwGpxd5GOw
          gpoC3pP36j5fOTk3lqIwPsFPtk0waKO2zrbpLzazzfw1FP40GNQJFLH7NQqtGgRHUyl2h
          TuVxduZY68X388wwx39sQOtShhn0UE8Mf7ADRF6pZfXEbhysdR17GVmfSVw9ey8mOG4Ub
          T83ipdjg/mpz1iMgVZ1D8ITsRx/Iv9oW6hq2oVn1r0Gh0QMdDTPLLD+7LFPTolS0zmeEF
          Rnx/sPLplHM6hFlQMHRo7vrbIF69L/xbDKOnc0VSEWrSwnE8tnqUhE4wzc8ukjbM/eMId
          v9sMwxU+Wunb7LBx1FbHrdMke3oEYP0mKMpbdhvmRaE9S3WykCUF2dI9yAEkRYrAZcdeJ
          gZMSkFzBbDzum71r834SvdofFXJC6N3kfP+LUSjirlUhOUxPz4715k5x2DVIbSgCCIcUW
          oAiT+Q9Ayfy02h7DhMl1K0wyczTRSTVqdV5gEXJSIK784iXw8Nj2itNwvHQyBc=
